version: "3.8"

services:

    app:
        build:
            args:
                user: laravel
                uid: 1000
            context: .
            dockerfile: docker/app.dockerfile
        image: djigit-app
        container_name: djigit-app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - .:/var/www/html:delegated
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - djigit-net

    nginx:
        image: nginx:1.17-alpine
        container_name: djigit-nginx
        restart: unless-stopped
        ports:
            - '${WEB_SERVER_PORT:-8080}:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - djigit-net

    db:
        image: 'mysql:8.0'
        container_name: djigit-db
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'djigit-mysql:/var/lib/mysql'
        networks:
            - djigit-net


networks:
    djigit-net:
        driver: bridge

volumes:
    djigit-mysql:
        driver: local

